ALTER TABLE app.pedidos DROP CONSTRAINT IF EXISTS pedidos_status_check;
ALTER TABLE app.pedidos ADD CONSTRAINT pedidos_status_check CHECK (
  status IN ('PENDING_PAYMENT','PAID','IN_PRODUCTION','READY_TO_SHIP','SHIPPED','DELIVERED','CANCELLED','REFUNDED','CHARGEBACK')
);
