import { useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { PageMeta } from '../../components/common/PageMeta.jsx'
import { customerForgot, customerReset } from '../../services/api.js'
import { useCustomerAuth } from '../../context/customerAuthContext.jsx'

export function CustomerAuthPage({mode}){
  const navigate=useNavigate();const [params]=useSearchParams();const { signIn, signUp } = useCustomerAuth();const [form,setForm]=useState({name:'',email:'',phone:'',password:'',token:params.get('token')??''});const [message,setMessage]=useState('');const [loading,setLoading]=useState(false)
  const update=(event)=>setForm({...form,[event.target.name]:event.target.value})
  const submit=async(event)=>{event.preventDefault();setLoading(true);setMessage('');try{if(mode==='register')await signUp({name:form.name,email:form.email,phone:form.phone,password:form.password});else if(mode==='login')await signIn({email:form.email,password:form.password});else if(mode==='forgot'){const result=await customerForgot({email:form.email});setMessage(result.data.developmentResetToken?`Ambiente de desenvolvimento: token ${result.data.developmentResetToken}`:'Se a conta existir, você receberá as instruções.');return}else await customerReset({token:form.token,password:form.password});navigate(params.get('next') || '/minha-conta',{replace:true})}catch(error){setMessage(error.message)}finally{setLoading(false)}}
  const titles={register:'Criar conta',login:'Entrar',forgot:'Recuperar senha',reset:'Redefinir senha'}
  return <section className="checkout-page container customer-auth-page"><PageMeta title={titles[mode]} description="Conta de cliente Brinco de Princesa." noindex/><form className="checkout-form customer-auth-form" onSubmit={submit}><p className="eyebrow">Conta Brinco de Princesa</p><fieldset><legend>{titles[mode]}</legend>{mode==='register'&&<><label>Nome<input name="name" value={form.name} onChange={update} required autoComplete="name"/></label><label>Telefone<input name="phone" value={form.phone} onChange={update} required autoComplete="tel"/></label></>}{mode!=='reset'&&<label>E-mail<input name="email" type="email" value={form.email} onChange={update} required autoComplete="email"/></label>}{mode==='reset'&&<label>Token de recuperação<input name="token" value={form.token} onChange={update} required/></label>}{mode!=='forgot'&&<label>Senha<input name="password" type="password" minLength="12" value={form.password} onChange={update} required autoComplete={mode==='login'?'current-password':'new-password'}/></label>}</fieldset><p className="customer-auth-message" role="status">{message}</p><button className="button button-primary" disabled={loading}>{loading?'Aguarde…':titles[mode]}</button>{mode==='login'&&<p className="customer-auth-links"><Link to="/recuperar-senha">Esqueci minha senha</Link><span aria-hidden="true">·</span><Link to="/cadastro">Criar conta</Link></p>}</form></section>
}
